### ISSUE TITLE
Undetected passes

### ISSUE THREAD

**Issue by EdwardDimaguila** [slacker87/CoreIR#2]
Hi Micheal,

I recently built this project transponder based on atmega 328. however i often missed laps especially when flying at high speeds through the sensor gate. 

I read your commits and seen several times that you've changed the int khz value and finally settled to 426, why is it so? AFAIK the TSOP7000 IR detector used in the ilaps sensor bridge calls for 455khz as per datasheet, Gareth and Mitch measured the original ilaps transponders to have around 460 khz carrier, could this be the cause of my missed laps?

**Comment by RaceFPV** [comment]
Potentially, but I've found that even stock ilap transponders have missed laps in certain conditions. Those conditions are: high speed flying, full sun directly on receiver gate. The sun emits a high enough amount of IR light that it effectively 'blinders' the receiver gate from properly seeing the transponders emitted IR led. Also please make sure your using version 2.0 as a _lot_ of improvements to readout were done for that build. One final note is that I used a logic analyzer to check the output of the IR pulses hitting the led from the arduino and it matches up 1 to 1 with the original boards. The original leds were picked so that ilap could dump direct uart out onto the led but with a bit of software magic that can be 'simulated' with software so that a different ir led can be used (as in this case). Hope this helps my apologies for the late response!

**Comment by isopix** [comment]
I do wonder which is better and would skip less laps:
 - I-Lap (CoreIR)
 - Robitronic/EasyLap (RiCino Next)

Hi,

Could you comment on difference between I-Lap and Robitronic(and EasyLap clone)?
Both use IR and both got reverse-engineered clones.

https://github.com/zelogik/RicinoNext
>    - Transmitter option: (cheap to expensive)
>        - Nothing -> led barrier, Only one car on the track. (cheapest...) (POSSIBLE TO ADAPT)
>        - IR -> RC5/Ricino/easytimer, 38khz, 110ms between each data pulse (POSSIBLE TO ADAPT)
>        - IR -> CoreIR/I-Lap, 370khz , 20 or 30ms between each data pulse ?!?
>       - IRDA -> Robitronic/Ezlap/etc.., 500us data pulse + 1-5ms waiting (DEFAULT VERSION)
>        - RFID -> Kyosho, passive RFID, 5-10mm max gap between loop and transmitter
>        - UHF -> AMBrc, active "RFID", look at github clone...

They also have Robitronic compatible transponder:
https://github.com/zelogik/RicinoNext/tree/main/Hardware/Emitter/irda_robi
https://github.com/zelogik/RicinoNext/tree/main/Software

Isn't Robitronic better than I-Lap?

I know there's also reverse-engineered AMBrc clone (called RCHourGlass), but it's probably overkill for 1:43 cars
